stages:
  - build
  - test
  - release

variables:
  SONARQUBE_TARGET: zoo,test
  SAST_TARGET: zoo
  PYLINT_TARGET: zoo
  PYTEST_COVERAGE_TARGET: zoo

include:
  - "https://ci-files.skypicker.com/templates/build/black.yml"
  - "https://ci-files.skypicker.com/templates/build/kaniko.yml"
  - "https://ci-files.skypicker.com/templates/build/pre_commit.yml"
  - "https://ci-files.skypicker.com/templates/linters/commit_style.yml"
  - "https://ci-files.skypicker.com/templates/release/release_latest.yml"
  - "https://ci-files.skypicker.com/templates/release/sonarqube_scan.yml"
  - "https://ci-files.skypicker.com/templates/test/container_scanning.yml"
  - "https://ci-files.skypicker.com/templates/test/dependency_scanning.yml"
  - "https://ci-files.skypicker.com/templates/test/pylint.yml"
  - "https://ci-files.skypicker.com/templates/test/pytest.yml"
  - "https://ci-files.skypicker.com/templates/test/sast.yml"

black:
  tags: []

commit-style:
  tags: []

docker_build:
  extends: .kaniko-build

dependency_scanning:
  tags: []

test_migrations:
  stage: test
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  services:
    - postgres:11-alpine
  variables:
    POSTGRES_HOST_AUTH_METHOD: trust
  script:
    - python manage.py makemigrations --check

release_latest:
  services:
    - docker:19.03-dind
