---
default_language_version:
  python: python3.8

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: debug-statements
      - id: no-commit-to-branch
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: detect-private-key
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: check-merge-conflict
      - id: requirements-txt-fixer

  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.12.0
    hooks:
      - id: gitlint

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.18.0
    hooks:
      - id: yamllint
        exclude: test/*

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.19.0
    hooks:
      - id: markdownlint
        language_version: system

  - repo: https://github.com/asottile/seed-isort-config
    rev: v1.9.3
    hooks:
      - id: seed-isort-config

  - repo: https://github.com/timothycrosley/isort
    rev: 4.3.21
    hooks:
      - id: isort
        # extra dependencies for config in pyproject.toml
        additional_dependencies: ["isort[pyproject]"]
        exclude: test\/.*\/snapshots\/*

  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black
        pass_filenames: false
        args: ["."]

  - repo: https://github.com/PyCQA/pydocstyle
    rev: 4.0.1
    hooks:
      - id: pydocstyle

  - repo: https://github.com/codingjoe/relint
    rev: 1.1.1
    hooks:
      - id: relint
