---
default_language_version:
  python: python3.8

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: debug-statements
      - id: no-commit-to-branch
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: detect-private-key
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: check-merge-conflict
      - id: requirements-txt-fixer

  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.15.0
    hooks:
      - id: gitlint

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.0
    hooks:
      - id: yamllint
        exclude: test/

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.26.0
    hooks:
      - id: markdownlint
        language_version: system

  - repo: https://github.com/timothycrosley/isort
    rev: 5.7.0
    hooks:
      - id: isort
        exclude: test.*snapshots/

  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        pass_filenames: false
        args: ["."]

  - repo: https://github.com/PyCQA/pydocstyle
    rev: 5.1.1
    hooks:
      - id: pydocstyle

  - repo: https://github.com/codingjoe/relint
    rev: 1.2.1
    hooks:
      - id: relint
