- name: Fix it now
  pattern: "[fF][iI][xX][mM][eE]"
  filename:
    - "*.py"

- name: No sys.path changes
  pattern: "sys\\.path\\.append|sys\\.path\\.insert"
  filename:
    - "zoo/**.py"

- name: IPython debug leftover
  pattern: "IPython\\.embed()"
  filename:
    - "*.py"

- name: Leftover print
  pattern: "print\\("
  filename:
    - "*.py"

- name: Use relative imports
  pattern: "import zoo\\.{{ cookiecutter.package_name }}|from zoo\\.{{ cookiecutter.package_name }}"
  filename:
    - "zoo/**.py"

- name: Unpinned requirement
  pattern: "^\\w+\\s"
  filename:
    - "*requirements*.txt"
