version: '2'
services:
  app:
    build: .
    command:
      - python
      - manage.py
      - runserver
      - '0.0.0.0:8080'
    ports:
      - 20966:8080
    environment:
      DATABASE_URL: 'postgres://postgres:postgres@postgres/postgres'
      ZOO_DEBUG: '1'
      ZOO_SLACK_URL:
      ZOO_GITLAB_URL:
      ZOO_SENTRY_URL:
      ZOO_SENTRY_ORGANIZATION:
      ZOO_AUDITING_CHECKS:
      WEB_CONCURRENCY:
    tty: true
    volumes:
      - ./zoo:/app/zoo
    depends_on:
      - postgres
      - webpack
      - redis
    restart: on-failure

  webpack:
    build: webpack
    volumes:
      - ./zoo/:/app/source
      - ./webpack/config:/app/config
    command:
      ["yarn", "development"]

  postgres:
    ports:
      - '5432'

  redis:
    ports:
      - '6379'

  scheduler:
    environment:
      ZOO_DEBUG: '1'
    volumes:
      - ./zoo:/app/zoo
      - /tmp/celerybeat-schedule:/tmp/celerybeat-schedule
    restart: on-failure

  worker:
    environment:
      DATABASE_URL: 'postgres://postgres:postgres@postgres/postgres'
      ZOO_DATADOG_API_KEY:
      ZOO_DATADOG_APP_KEY:
      ZOO_DEBUG: '1'
      ZOO_GITLAB_URL:
      ZOO_GITLAB_DB_URL:
      ZOO_GITLAB_TOKEN:
      ZOO_PINGDOM_EMAIL:
      ZOO_PINGDOM_PASS:
      ZOO_PINGDOM_APP_KEY:
      ZOO_SENTRY_URL:
      ZOO_SENTRY_ORGANIZATION:
      ZOO_SENTRY_API_KEY:
      ZOO_AUDITING_CHECKS:
    volumes:
      - ./zoo:/app/zoo
    restart: on-failure
