[tool.black]
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | __pycache__

  # All of the above are the default values for black exclude. Specify custom bellow.
  | test\/.*\/snapshots\/*
  | .pre-commit-cache/*
)/
'''

[tool.isort]
# config compatible with Black
line_length = 88
multi_line_output = 3
default_sectiont = "THIRDPARTY"
include_trailing_comma = true
known_third_party = ["arrow", "attr", "boto3", "celery", "datadog", "dateutil", "ddtrace", "django", "djangoql", "environ", "factory", "faker", "fakeredis", "freezegun", "github", "gitlab", "google", "googleapiclient", "graphene", "graphene_django", "graphql_relay", "httpretty", "jsonschema", "kubernetes", "markdown", "pkg_resources", "prance", "pygerduty", "pytest", "pytest_factoryboy", "raven", "redis", "requests", "setuptools", "slacker", "snapshottest", "structlog", "testing", "urllib3", "yaml"]
