name: Pull request
on: [pull_request]

jobs:
  bento:
    runs-on: ubuntu-latest
    name: Bento
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Bento
        id: bento
        uses: returntocorp/bento-action@v1
        with:
          acceptTermsWithEmail: platform@kiwi.com
