name: Release
on:
  push:
    tags:
      - "v*"

jobs:
  container:
    name: Container image
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: GitHub Package Registry
        uses: aevea/action-kaniko@master
        with:
          registry: docker.pkg.github.com
          password: ${{ secrets.GITHUB_TOKEN }}
          image: server
          cache: true
          cache_registry: cache

      - name: Dockerhub
        uses: aevea/action-kaniko@master
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          image: kiwicom/the-zoo
          cache: true
          cache_registry: kiwicom/cache

  release-notes:
    name: Release Notes
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Generate changelog
        uses: docker://aevea/release-notary
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
