name: Release
on:
  push:
    tags:
      - "v*"

jobs:
  release-notes:
    name: Release Notes
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Release Notary Action
        uses: docker://commitsar/release-notary
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
